### ISSUE TITLE
test.py Traceback (most recent call last):   File "/home/learner/PCC-Net-ori_pt1_py3/test.py", line 198, in <module>     main()   File "/home/learner/PCC-Net-ori_pt1_py3/test.py", line 77, in main     test(file_list[1], model_path, roi) IndexError: list index out of range

### ISSUE THREAD

**Issue by sqzhen** [gjy3035/PCC-Net#23]

**Comment by sqzhen** [comment]
出现这个问题，应该怎么改

**Comment by sqzhen** [comment]
请问，在测试代码中，出现IndexError: list index out of range应该怎么改

**Comment by FCgogogo** [comment]
我也遇到了相同的问题
